### ISSUE TITLE
Defining Structure for Using ESP KNX on TASMOTA

### ISSUE THREAD

**Issue by ascillato** [ascillato/ESP-KNX-IP_Lite#1]
@sisamiwe, do you think of using **xdrv_08_knx.ino** as a base for KNX on Tasmota?

**Comment by sisamiwe** [comment]
@ascillato 
I think this would be a good starting point.

In a german based forum, there are some guys having already some sketches build. These sketches have basic functionality for SONOFF and KNX.

Here is the one for the 4channel SONOFF:
`/*
* Sonoff 4ch Pro mit KNX Anbindung
*/

#include <esp-knx-ip.h>

// WiFi config
const char* ssid = "SSID";    //change to your SSID
const char* pass = "PW";      //change to your PSK

//GPIOs
int Ch1_Pin = 12;
int Ch2_Pin = 5;
int Ch3_Pin = 4;
int Ch4_Pin = 15;
int Button1_Pin = 0;
int Button2_Pin = 9;
int Button3_Pin = 10;
int Button4_Pin = 14;
int LED_Pin = 13;

//States
int Button1State = 0;
int Button2State = 0;
int Button3State = 0;
int Button4State = 0;
int lastButton1State = 1;
int lastButton2State = 1;
int lastButton3State = 1;
int lastButton4State = 1;
int Ch1State = 0;
int Ch2State = 0;
int Ch3State = 0;
int Ch4State = 0;

//Groupadresses
config_id_t Ch1Ack_GA;
config_id_t Ch2Ack_GA;
config_id_t Ch3Ack_GA;
config_id_t Ch4Ack_GA;
config_id_t Watchdog_GA;

config_id_t hostname_id;

void Ch1_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_WRITE:
        digitalWrite(Ch1_Pin, *data);
        knx.write1Bit(knx.config_get_ga(Ch1Ack_GA), *data);
        break;
    }
}

void Ch1State_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_READ:
        Ch1State = digitalRead(Ch1_Pin);
        knx.answer1Bit(knx.config_get_ga(Ch1Ack_GA), Ch1State);
        break;
    }
}

void Ch2_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_WRITE:
        digitalWrite(Ch2_Pin, *data);
        knx.write1Bit(knx.config_get_ga(Ch2Ack_GA), *data);
        break;
    }
}

void Ch2State_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_READ:
        Ch2State = digitalRead(Ch2_Pin);
        knx.answer1Bit(knx.config_get_ga(Ch2Ack_GA), Ch2State);
        break;
    }
}

void Ch3_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_WRITE:
        digitalWrite(Ch3_Pin, *data);
        knx.write1Bit(knx.config_get_ga(Ch3Ack_GA), *data);
        break;
    }
}

void Ch3State_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_READ:
        Ch3State = digitalRead(Ch3_Pin);
        knx.answer1Bit(knx.config_get_ga(Ch3Ack_GA), Ch3State);
        break;
    }
}

void Ch4_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_WRITE:
        digitalWrite(Ch4_Pin, *data);
        knx.write1Bit(knx.config_get_ga(Ch4Ack_GA), *data);
        break;
    }
}

void Ch4State_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_READ:
        Ch4State = digitalRead(Ch4_Pin);
        knx.answer1Bit(knx.config_get_ga(Ch4Ack_GA), Ch4State);
        break;
    }
}

void Watchdog_callback(knx_command_type_t ct, address_t const &received_on, uint8_t data_len, uint8_t *data)
{
    switch (ct)
    {
      case KNX_CT_READ:
        knx.answer1Bit(knx.config_get_ga(Watchdog_GA), 1);
        break;
    }
}

void setup() {
    pinMode(LED_Pin, OUTPUT);

    pinMode(Ch1_Pin, OUTPUT);
    pinMode(Ch2_Pin, OUTPUT);
    pinMode(Ch3_Pin, OUTPUT);
    pinMode(Ch4_Pin, OUTPUT);
    pinMode(Button1_Pin, INPUT_PULLUP);
    pinMode(Button2_Pin, INPUT_PULLUP);
    pinMode(Button3_Pin, INPUT_PULLUP);
    pinMode(Button4_Pin, INPUT_PULLUP);
    Serial.begin(9600);

    // Register the callbacks
    knx.register_callback("Kanal 1 Schalten", Ch1_callback);
    knx.register_callback("Kanal 1 Rückmeldung", Ch1State_callback);
    knx.register_callback("Kanal 2 Schalten", Ch2_callback);
    knx.register_callback("Kanal 2 Rückmeldung", Ch2State_callback);
    knx.register_callback("Kanal 3 Schalten", Ch3_callback);
    knx.register_callback("Kanal 3 Rückmeldung", Ch3State_callback);
    knx.register_callback("Kanal 4 Schalten", Ch4_callback);
    knx.register_callback("Kanal 4 Rückmeldung", Ch4State_callback);
    knx.register_callback("Watchdog", Watchdog_callback);

    // Register the group addresses
    Ch1Ack_GA = knx.config_register_ga("Kanal 1 Rückmeldung");
    Ch2Ack_GA = knx.config_register_ga("Kanal 2 Rückmeldung");
    Ch3Ack_GA = knx.config_register_ga("Kanal 3 Rückmeldung");
    Ch4Ack_GA = knx.config_register_ga("Kanal 4 Rückmeldung");
    Watchdog_GA = knx.config_register_ga("Watchdog");

    // And the config options
    hostname_id = knx.config_register_string("Hostname", 20, String("4CH_PRO"));

    // Load previous values from EEPROM
    knx.load();

    // Init WiFi
    WiFi.hostname(knx.config_get_string(hostname_id));
    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, pass);

    Serial.println("");
    Serial.print("[Connecting]");
    Serial.print(ssid);

    digitalWrite(LED_Pin, LOW);
    while (WiFi.status() != WL_CONNECTED) {
        digitalWrite(LED_Pin, HIGH);
        delay(500);
        Serial.print(".");
        digitalWrite(LED_Pin, LOW);
    }
    digitalWrite(LED_Pin, HIGH);

    // Start knx
    knx.start();

    Serial.println();
    Serial.println("Connected to wifi");
    Serial.println(WiFi.localIP());
    Serial.println(" ");
}

void loop() {
    // Process knx events, e.g. webserver
    knx.loop();

//Toggeln der Kanäle bei Positiver Flanke der Buttons
    Button1State = digitalRead(Button1_Pin);
    Ch1State = digitalRead(Ch1_Pin);
    if (Button1State != lastButton1State) {
      if (Button1State == LOW) {
        if (Ch1State == 1) {
          digitalWrite(Ch1_Pin, LOW);
          knx.write1Bit(knx.config_get_ga(Ch1Ack_GA), 0);
          }
          else if (Ch1State == 0){
          digitalWrite(Ch1_Pin, HIGH);
          knx.write1Bit(knx.config_get_ga(Ch1Ack_GA), 1);
          }
      }  
    }
    lastButton1State = Button1State;

    Button2State = digitalRead(Button2_Pin);
    Ch2State = digitalRead(Ch2_Pin);
    if (Button2State != lastButton2State) {
      if (Button2State == LOW) {
        if (Ch2State == 1) {
          digitalWrite(Ch2_Pin, LOW);
          knx.write1Bit(knx.config_get_ga(Ch2Ack_GA), 0);
          }
          else if (Ch2State == 0){
          digitalWrite(Ch2_Pin, HIGH);
          knx.write1Bit(knx.config_get_ga(Ch2Ack_GA), 1);
          }
      }  
    }
    lastButton2State = Button2State;

    Button3State = digitalRead(Button3_Pin);
    Ch3State = digitalRead(Ch3_Pin);
    if (Button3State != lastButton3State) {
      if (Button3State == LOW) {
        if (Ch3State == 1) {
          digitalWrite(Ch3_Pin, LOW);
          knx.write1Bit(knx.config_get_ga(Ch3Ack_GA), 0);
          }
          else if (Ch3State == 0){
          digitalWrite(Ch3_Pin, HIGH);
          knx.write1Bit(knx.config_get_ga(Ch3Ack_GA), 1);
          }
      }  
    }
    lastButton3State = Button3State;

    Button4State = digitalRead(Button4_Pin);
    Ch4State = digitalRead(Ch4_Pin);
    if (Button4State != lastButton4State) {
      if (Button4State == LOW) {
        if (Ch4State == 1) {
          digitalWrite(Ch4_Pin, LOW);
          knx.write1Bit(knx.config_get_ga(Ch4Ack_GA), 0);
          }
          else if (Ch4State == 0){
          digitalWrite(Ch4_Pin, HIGH);
          knx.write1Bit(knx.config_get_ga(Ch4Ack_GA), 1);
          }
      }  
    }
    lastButton4State = Button4State;

  delay(50);  
}`
Does this help?

**Comment by ascillato** [comment]
wow! nice. Looking to it ....

**Comment by ascillato** [comment]
Do you have any KNX device?

**Comment by sisamiwe** [comment]
Yes, i do have multiple knx devices.
Also the is a sw knd router avsible to be run on raspberry gor example. https://github.com/knxd/knxd
Using that allows for testing since this package has also the tools fir write and listen on the knx bus. What i mean is, thar the knxd and the sonoff eirh your Firmware create the knx bud

**Comment by ascillato** [comment]
Great! I was struggling with the raspberry jessy image from knx with the gateway trying to see the packages. With knxd it should be easier
Thanks :+1:

**Comment by ascillato** [comment]
Could you use knxd ?
I can not start it. It say that the port is open and then crash but nothing is responding. I will re read the docs.
Since I need some tool to see the telegrams and also to test over HomeAssistant.

**Comment by sisamiwe** [comment]
I'm using knxd and it works fine.
Maybe the easiest way is to use Onkel Andys image for smarthomeNG. 
See here: https://sourceforge.net/p/smarthomeng-raspi-image/wiki/Home/

knxd is part of that image and a bit more.
So I'm unsing also this image and smarthomeNG as hub for all my smarthome.

**Comment by ascillato** [comment]
Nice, I'll test that!

**Comment by ascillato** [comment]
Hi,

I could make work the envy/ESP-KNX-IP on Home Assistant. Now I can develop some tests there.

I put an issue on XKNX because it expects that the last part of the telegram (APDU) is 1 byte, But envy/ESP-KNX-IP send 2 bytes (as the KNX protocol say). I modify the envy/ESP-KNX-IP library so as to send 1 byte now for testing. And works great and really fast. But I think that there is something wrong on XKNX. We will see that later.

Right now, I have tested the 2 examples of envy and make them work on Home Assistant.

I have on the same Raspberry Pi: KNXd server and Home Assistant with the latests XKNX (manually installed). So I can now test the comms flux there.

Could you make the envy/ESP-KNX-IP works with your KNX installation?

**Comment by sisamiwe** [comment]
Hi,
sounds great.

Yes, I've it ESP-KNX-IP running. I'm using a Wemos D1 mini with Bosch BME280 Breakout Board and the example file "envirnmental sensor" of the envy/ESP-KNX-IP github.

It works.

**Comment by ascillato** [comment]
Now making the **_xdrv_08_KNX.ino_** on [Sonoff-Tasmota_KNX](https://github.com/ascillato/Sonoff-Tasmota_KNX), a forked version of [Original Tasmota](https://github.com/arendst/Sonoff-Tasmota) v5.12.0d (7/march/2018)

This driver requires the [ascillato/ESP-KNX-IP_Lite](https://github.com/ascillato/ESP-KNX-IP_Lite), a forked and modified version of [envy/esp-knx-ip](https://github.com/envy/esp-knx-ip)

The Modifications from the Original Tasmota are going to be:
* Adding the file _/sonoff/xdrv_08_KNX.ino_ 
* Add the entry `#define USE_KNX` on _/sonoff/user_config.h_
* Replace the file _/sonoff/webserver.ino_

When I reach a preliminary version I will post the info here. Then, when we have a working version, we can make the Pull Request to Tasmota

**Comment by ascillato** [comment]
Basic functionality available.

**Comment by ascillato** [comment]
Added a Road Map to the readme of  https://github.com/ascillato/Sonoff-Tasmota_KNX
